name: Run Custom R Script

on:
  workflow_dispatch:
    inputs:
      script_name:
        description: 'Path to the R script to run (e.g. scripts/analysis.R)'
        required: true
        default: 'script.R'

jobs:
  run-r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("tidyverse"), repos="https://cloud.r-project.org")'

      - name: Run chosen script
        run: |
          Rscript "${{ github.event.inputs.script_name }}"
